# Generated by Django 3.2.18 on 2023-05-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='level',
            field=models.CharField(default='', max_length=255),
        ),
    ]
