# Generated by Django 3.2.15 on 2023-02-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_department_staffs_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='department_id',
            new_name='department',
        ),
    ]
