# Generated by Django 3.2.18 on 2023-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230326_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='block_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
