# Generated by Django 3.2.18 on 2023-05-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_timeslot_education_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='Education_level',
            new_name='education_level',
        ),
    ]
