# Generated by Django 3.2.15 on 2023-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_department_id_staffs_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.AddField(
            model_name='students',
            name='program',
            field=models.CharField(default='', max_length=255),
        ),
    ]
