# Generated by Django 3.2.18 on 2023-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_education_level_timeslot_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='block_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
