# Generated by Django 3.2.16 on 2023-05-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_students_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
