# Generated by Django 3.2.16 on 2023-02-21 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_time_slots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='time_slots',
            new_name='TimeSlot',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
