# Generated by Django 3.2.16 on 2023-05-13 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_notificationstaff_notificationstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
