# Generated by Django 3.2.16 on 2023-02-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20230221_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='slot_time',
            new_name='time',
        ),
    ]
