# Generated by Django 3.2.16 on 2023-02-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_slot_time_timeslot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
