# Generated by Django 3.2.16 on 2023-02-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='student',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
