# Generated by Django 3.2.16 on 2023-02-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20230227_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='staff',
            new_name='staffId',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='student',
            new_name='studentId',
        ),
    ]
