# Generated by Django 3.2.16 on 2023-02-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20230227_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='studentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.customuser'),
            preserve_default=False,
        ),
    ]
